language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-accel

os:
  - windows
  - linux
  - osx

python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

matrix:
  allow_failures:
      - python: "nightly"

install:
  - python -m pip install -U pip
  - pip install -e .

script:
  - py.test tests/

skip_join: false
